### ISSUE TITLE
Feature request: enable shortened methods preview

### ISSUE THREAD

**Issue by FeepingCreature** [funkwerk-mobility/cogito#2]
Methods of the form

```
int foo() => 3;
```
are currently not understood by Cogito. In DMD this is enabled by `preview=shortenedMethods`, but Cogito doesn't understand the DMD flags.

This can be fixed by setting `global.params.shortenedMethods = true;` after initializing DMD, and since it's a strict syntax addition, there shouldn't be any problem from having it always on.

**Comment by belka-ew** [comment]
It's in 1.4.1.

I also tried to update the frontend to 2.101, but there are unfortunately some errors.

**Comment by belka-ew** [comment]
Updated the frontend to v2.101.2. I'm closing the issue now. Feel free to reopen if there is something else to do.
